image: docker:latest
variables:
  REPOSITORY_URL: 249362495243.dkr.ecr.us-east-2.amazonaws.com
  REPO_NAME: $CI_PROJECT_NAME
  GIT_SUBMODULE_STRATEGY: normal
  REGION: us-east-2
stages:
  - build-init
  - build-test
#  - build-dev
#  - build-staging
#  - build-production
#  - deploy-test
#  - deploy-dev
#  - deploy-staging
#  - deploy-production


build-init:
  stage: build-init
  before_script:
    - apk add --no-cache curl jq python py-pip git
    - pip install awscli
    - git submodule update --remote
  script:
    - $(aws ecr get-login --no-include-email --region $REGION)
    - aws ecr create-repository --repository-name $REPO_NAME --region $REGION || echo "success"
  only:
    - init
build-test:
  stage: build-test
  before_script:
    - apk add --no-cache curl jq python py-pip git
    - pip install awscli
    - git submodule update --remote
  script:
    - $(aws ecr get-login --no-include-email --region $REGION)
    - docker build -t $REPO_NAME:latest .
    - docker tag $REPO_NAME:latest $REPOSITORY_URL/$REPO_NAME:latest
    - docker push $REPOSITORY_URL/$REPO_NAME:latest
  only:
    - master
#
#deploy-test:
#  stage: deploy-test
#  script:
#    - upgrade --environment dev --stack services-test --service hotel-booking-test
#  environment:
#    name: test
#    url: https://test-micro-services.vntrip.vn/hotel-booking
#  only:
#    - test