image: trungcong24/docker
variables:
  REPOSITORY_URI: 249362495243.dkr.ecr.us-east-2.amazonaws.com
  REPO_NAME: $CI_PROJECT_NAME
  GIT_SUBMODULE_STRATEGY: normal
  AWS_DEFAULT_REGION: us-east-2
  SERVICE_NAME: $CI_PROJECT_NAME-service
  ROUTE: test1
stages:
  - build-test
#  - build-staging
#  - build-production
  - deploy-test
#  - deploy-staging
#  - deploy-production

build-test:
  stage: build-test
  before_script:
    - git submodule update --remote
  script:
    - $(aws ecr get-login --no-include-email)
    - sh ./create_repo.sh
    - docker build -t $REPOSITORY_URI/$REPO_NAME:latest .
    - docker push $REPOSITORY_URI/$REPO_NAME:latest
  only:
    - master

deploy-test:
  stage: deploy-test
  before_script:
    - export CLUSTER=test
    - export FAMILY=${REPO_NAME}_${CLUSTER}
    - export VPCID=vpc-b7e5bcdf
    - export ALB_LISTENER=arn:aws:elasticloadbalancing:us-east-2:249362495243:listener/app/test/8913e94197cf1cd2/f4578621b4031287
  script:
    - $(aws ecr get-login --no-include-email)
    - sh ./deploy.sh
  only:
    - master
  when: on_success