image: trungcong24/docker
variables:
  REPOSITORY_URL: 249362495243.dkr.ecr.us-east-2.amazonaws.com
  REPO_NAME: $CI_PROJECT_NAME
  GIT_SUBMODULE_STRATEGY: normal
  AWS_DEFAULT_REGION: us-east-2
  SERVICE_NAME: $CI_PROJECT_NAME-service
stages:
  - build-init
  - build-test
#  - build-dev
#  - build-staging
#  - build-production
  - deploy-test
#  - deploy-dev
#  - deploy-staging
#  - deploy-production


build-init:
  stage: build-init
  before_script:
    - git submodule update --remote
  script:
    - $(aws ecr get-login --no-include-email)
    - aws ecr create-repository --repository-name $REPO_NAME || echo "success"
  only:
    - init
build-test:
  stage: build-test
  before_script:
    - export FAMILY=test-services
    - git submodule update --remote
  script:
    - $(aws ecr get-login --no-include-email)
    - docker build -t $REPO_NAME:latest .
    - docker tag $REPO_NAME:latest $REPOSITORY_URL/$REPO_NAME:latest
    - docker push $REPOSITORY_URL/$REPO_NAME:latest
  only:
    - master

deploy-test:
  stage: deploy-test
  script:
    - export FAMILY=${REPO_NAME}_test
    - export CLUSTER=test
    - $(aws ecr get-login --no-include-email)
    - sh ./deploy.sh
  only:
    - master
  when: on_success